const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { parse } = require('json2csv');

const formatValue = (val) => val ? String(val).substring(0, 30) : '-';
const formatDate = (date) => date ? new Date(date).toLocaleDateString() : '-';

exports.generatePDFReport = (tickets, appliedFilters, stats, user, res) => {
  const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape', bufferPages: true });
  
  res.setHeader('Content-Type', 'application/pdf');
  const dateStr = new Date().toISOString().split('T')[0];
  res.setHeader('Content-Disposition', `attachment; filename=Ticket_Report_${dateStr}.pdf`);
  
  doc.pipe(res);

  const drawHeader = () => {
    doc.fontSize(16).text('IT Help Desk Ticketing System', { align: 'center' });
    doc.fontSize(12).text('Ticket Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).text(`Generated by: ${user.name}`);
    doc.text(`Generated on: ${new Date().toLocaleString()}`);
    doc.moveDown();
    
    // Filters
    doc.fontSize(12).text('Applied Filters:', { underline: true });
    doc.fontSize(10);
    const filterKeys = Object.keys(appliedFilters);
    if (filterKeys.length === 0) {
      doc.text('None');
    } else {
      filterKeys.forEach(k => doc.text(`${k}: ${appliedFilters[k]}`));
    }
    doc.moveDown();

    // Summary Stats
    doc.fontSize(12).text('Summary Statistics:', { underline: true });
    doc.fontSize(10);
    doc.text(`Total Tickets: ${stats.total || 0} | Open: ${stats.open || 0} | Assigned: ${stats.assigned || 0} | In Progress: ${stats.inProgress || 0}`);
    doc.text(`Resolved: ${stats.resolved || 0} | Closed: ${stats.closed || 0} | Critical: ${stats.critical || 0}`);
    doc.text(`Average Resolution Time: ${stats.avgResolutionTime || 'N/A'}`);
    doc.moveDown(2);
  };

  drawHeader();

  // Table
  const tableTop = doc.y;
  let y = tableTop;

  const cols = [
    { name: 'ID', x: 30, w: 40 },
    { name: 'Title', x: 70, w: 100 },
    { name: 'Dept', x: 170, w: 70 },
    { name: 'Category', x: 240, w: 60 },
    { name: 'Priority', x: 300, w: 50 },
    { name: 'Status', x: 350, w: 60 },
    { name: 'Employee', x: 410, w: 80 },
    { name: 'Agent', x: 490, w: 80 },
    { name: 'Created', x: 570, w: 60 },
    { name: 'Updated', x: 630, w: 60 },
    { name: 'Resolved', x: 690, w: 60 },
    { name: 'Closed', x: 750, w: 60 }
  ];

  doc.fontSize(8).font('Helvetica-Bold');
  cols.forEach(c => doc.text(c.name, c.x, y, { width: c.w }));
  y += 15;
  doc.moveTo(30, y).lineTo(810, y).stroke();
  y += 5;

  doc.font('Helvetica');
  tickets.forEach((t, i) => {
    if (y > 500) {
      doc.addPage();
      y = 30;
      doc.fontSize(8).font('Helvetica-Bold');
      cols.forEach(c => doc.text(c.name, c.x, y, { width: c.w }));
      y += 15;
      doc.moveTo(30, y).lineTo(810, y).stroke();
      y += 5;
      doc.font('Helvetica');
    }
    
    doc.text(String(t._id).slice(-6).toUpperCase(), cols[0].x, y, { width: cols[0].w, lineBreak: false });
    doc.text(formatValue(t.title), cols[1].x, y, { width: cols[1].w, lineBreak: false });
    doc.text(t.department?.name || '-', cols[2].x, y, { width: cols[2].w, lineBreak: false });
    doc.text(t.category, cols[3].x, y, { width: cols[3].w, lineBreak: false });
    doc.text(t.priority, cols[4].x, y, { width: cols[4].w, lineBreak: false });
    doc.text(t.status, cols[5].x, y, { width: cols[5].w, lineBreak: false });
    doc.text(t.createdBy?.name || '-', cols[6].x, y, { width: cols[6].w, lineBreak: false });
    doc.text(t.assignedTo?.name || '-', cols[7].x, y, { width: cols[7].w, lineBreak: false });
    doc.text(formatDate(t.createdAt), cols[8].x, y, { width: cols[8].w, lineBreak: false });
    doc.text(formatDate(t.updatedAt), cols[9].x, y, { width: cols[9].w, lineBreak: false });
    doc.text(formatDate(t.resolvedAt), cols[10].x, y, { width: cols[10].w, lineBreak: false });
    doc.text(formatDate(t.closedAt), cols[11].x, y, { width: cols[11].w, lineBreak: false });
    
    y += 15;
    doc.moveTo(30, y).lineTo(810, y).dash(1, {space: 2}).stroke().undash();
    y += 5;
  });

  const addPageFooter = () => {
    let pages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
    for (let i = 0; i < pages; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).font('Helvetica');
      doc.text('IT Help Desk Ticketing System', 30, doc.page.height - 40, { lineBreak: false });
      doc.text(`Generated by: ${user.name} | Generated on: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`, 200, doc.page.height - 40, { lineBreak: false });
      doc.text(`Page ${i + 1} of ${pages}`, doc.page.width - 80, doc.page.height - 40, { lineBreak: false });
    }
  };

  doc.on('pageAdded', () => {
    // Keep space for footer
    doc.page.margins.bottom = 50;
  });

  // Footer
  addPageFooter();
  doc.end();
};

exports.generateExcelReport = async (tickets, appliedFilters, stats, user, res) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = user.name;
  workbook.created = new Date();

  // Sheet 1: Dashboard Summary
  const summarySheet = workbook.addWorksheet('Dashboard Summary');
  summarySheet.columns = [
    { header: 'Metric', key: 'metric', width: 30 },
    { header: 'Value', key: 'value', width: 50 }
  ];
  
  summarySheet.addRow({ metric: 'Company', value: 'IT Help Desk Ticketing System' });
  summarySheet.addRow({ metric: 'Generated By', value: user.name });
  summarySheet.addRow({ metric: 'Generated On', value: new Date().toLocaleString() });
  summarySheet.addRow({});
  
  summarySheet.addRow({ metric: '--- Applied Filters ---', value: '' });
  Object.keys(appliedFilters).forEach(k => {
    summarySheet.addRow({ metric: k, value: appliedFilters[k] });
  });
  summarySheet.addRow({});

  summarySheet.addRow({ metric: '--- Summary Statistics ---', value: '' });
  summarySheet.addRow({ metric: 'Total Tickets', value: stats.total || 0 });
  summarySheet.addRow({ metric: 'Open', value: stats.open || 0 });
  summarySheet.addRow({ metric: 'Assigned', value: stats.assigned || 0 });
  summarySheet.addRow({ metric: 'In Progress', value: stats.inProgress || 0 });
  summarySheet.addRow({ metric: 'Resolved', value: stats.resolved || 0 });
  summarySheet.addRow({ metric: 'Closed', value: stats.closed || 0 });
  summarySheet.addRow({ metric: 'Critical', value: stats.critical || 0 });
  summarySheet.addRow({ metric: 'Average Resolution Time', value: stats.avgResolutionTime || 'N/A' });

  // Sheet 2: Ticket Details
  const detailsSheet = workbook.addWorksheet('Ticket Details');
  detailsSheet.columns = [
    { header: 'Ticket ID', key: 'id', width: 15 },
    { header: 'Title', key: 'title', width: 40 },
    { header: 'Department', key: 'dept', width: 20 },
    { header: 'Category', key: 'category', width: 15 },
    { header: 'Priority', key: 'priority', width: 15 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Employee', key: 'employee', width: 20 },
    { header: 'Assigned Agent', key: 'agent', width: 20 },
    { header: 'Created Date', key: 'created', width: 20 },
    { header: 'Last Updated', key: 'updated', width: 20 },
    { header: 'Resolved Date', key: 'resolved', width: 20 },
    { header: 'Closed Date', key: 'closed', width: 20 },
  ];

  tickets.forEach(t => {
    detailsSheet.addRow({
      id: String(t._id).slice(-6).toUpperCase(),
      title: t.title,
      dept: t.department?.name || '-',
      category: t.category,
      priority: t.priority,
      status: t.status,
      employee: t.createdBy?.name || '-',
      agent: t.assignedTo?.name || '-',
      created: formatDate(t.createdAt),
      updated: formatDate(t.updatedAt),
      resolved: formatDate(t.resolvedAt),
      closed: formatDate(t.closedAt)
    });
  });

  const dateStr = new Date().toISOString().split('T')[0];
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename=Ticket_Report_${dateStr}.xlsx`);
  
  await workbook.xlsx.write(res);
  res.end();
};

exports.generateCSVReport = (tickets, res) => {
  const fields = [
    { label: 'Ticket ID', value: row => String(row._id).slice(-6).toUpperCase() },
    { label: 'Title', value: 'title' },
    { label: 'Department', value: row => row.department?.name || '-' },
    { label: 'Category', value: 'category' },
    { label: 'Priority', value: 'priority' },
    { label: 'Status', value: 'status' },
    { label: 'Employee', value: row => row.createdBy?.name || '-' },
    { label: 'Assigned Agent', value: row => row.assignedTo?.name || '-' },
    { label: 'Created Date', value: row => formatDate(row.createdAt) },
    { label: 'Last Updated', value: row => formatDate(row.updatedAt) },
    { label: 'Resolved Date', value: row => formatDate(row.resolvedAt) },
    { label: 'Closed Date', value: row => formatDate(row.closedAt) }
  ];

  try {
    const csv = parse(tickets, { fields });
    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename=Ticket_Report_${dateStr}.csv`);
    res.send(csv);
  } catch (err) {
    console.error(err);
    res.status(500).send('Error generating CSV');
  }
};
